@startuml


left to right direction

class Gæst {
    Navn
    Telefon
    Email
    SamtykkeStatus
    NuværendeStatus
    SærligeHensyn
}


class Kommune{
    KommuneNavn
    EANNummer
}

class PodcastEpisode {
    Titel
    Dato
    Tid
    Status
    Mødested 
    Note
}


class JournalSystem{
    Gæst
    StartDato
    SlutDato
    Kontrakter
    Notering
    AktivitetsStatus
}

class Borger {
    CPR-Nummer
    JobStatus
    JobType

}
class Sagsbehandler{
    Navn
    SamtykkeStatus
    Afdeling
    Borger
    Telefon
    Email
    
}



PodcastEpisode "1" -- "1..*" Gæst 
Gæst "0..*"-- "   1" JournalSystem
Sagsbehandler "1" -- "0..*" PodcastEpisode
Borger "1" -- "1" Gæst
Sagsbehandler "0..*" -- "1"Kommune
Sagsbehandler "1..*" -- "1"Borger
hide circle
hide methods

@enduml
