@startuml BPMN Soul and Talk
!define BPMN_ENTITY entity

skinparam ActivityStartColor white
skinparam ActivityEndColor black

title BPMN: Aktivitetsflow for Soul and Talk

|#White|Kommunen|
start
:Uddelegerer opgave til Sagsbehandler;

|#White|Sagsbehandler|
:Bestiller en socialrådgiver og coach til privat borger;
repeat
:Skaffer samtykkeerklæring;
:Kontakter socialrådgiver;
  repeat while (Samtykkeerlæring er underskrevet af borger) is (     Nej) not (Ja)
  :Kontakt socialrådgiver;

|Socialrådgiver|
:Modtager bestilling;
:Bekræfter samtykkeerklæring;



|Socialrådgiver|
  :Socialrådgiver kontakter borger;
  |Podcast Episode|
  :Aftal dato og mødested;
  note right: Jf. Domænemodel:\n Til mødet med borger noteres borgers jobtype, \njobstatus, CPRnummer, nuværende status og særlige hensyn.
stop


footer Proces baseret på Soul and Talk
@enduml