@startuml Domænemodel


left to right direction

class Gæst {
    Navn
    Telefon
    Email
}


class Kommune{
    KommuneNavn
    EANNummer
}

class PodcastEpisode {
    Titel
    Dato
    Tid
    Status
    Mødested 
    Note
}

class Borger {
    CPR-Nummer
    JobStatus
    JobType
    SamtykkeStatus
    NuværendeStatus
    SærligeHensyn
}
class Sagsbehandler{
    Navn
    Afdeling
    Telefon
    Email
}



PodcastEpisode "0..*" -- "1..*" Gæst 
Sagsbehandler "1" -- "0..*" PodcastEpisode
Borger "1" -- "1" Gæst
Sagsbehandler "0..*" -- "1"Kommune
Sagsbehandler "1" -- "0..*"Borger

hide circle
hide methods

@enduml
