@startuml
skinparam classAttributeIconSize 0



package "ViewModels (Application)"{
    class MainViewmodels {
        
    }
}

package "Persistence (Repositories)" {

class GuestRepository{

}

class CaseOfficerRepository{

}

class CitizenRepository{

}

class LocalAuthorityRepository{

}

class PodcastEpisodeRepository{

}

class JournalRepository{

}

}

package "Models (Domain)" {
class LocalAuthority {
    - localAuthorityName : String
    - eanNummer : String

     + <<Constructor>> LocalAuthority()
}

class CaseOfficer {
    - name : String
    - department : String
    - phone : String
    - email : String
    
     + <<Constructor>> CaseOfficer()
}

class PodcastEpisode {
    - title : String
    - Date : Date
    - time : Time
    - status : String
    - meetingPlace : String
    - note : String

    + <<Constructor>> PodcastEpisode()
}

class Citizen {
    - cprNumber : String
    - workStatus : String
    - workType : String
    - consentStatus : String
    - currentStatus : String
    - specialConsiderations : String

    + <<Constructor>> Citizen()
}

class Guest {
    - name : String
    - phone : String
    - email : String
    - consentStatus : String

     + <<Constructor>> Guest()
}

class Journal {
    - startDate : Date
    - endDate : Date
    
     + <<Constructor>> Journal()
}

}
hide circle
@enduml