@startuml PackageDiagram for Soul&Talk

left to right direction
skinparam packageStyle rectangle
skinparam packageFontSize 14

package "UI" as UI {
    package "MainWindow"
}

package "APPLICATION" as APPLICATION {
    package "MainViewModel"
    package "Use Cases" as USECASES {
        package "UC1: Create Citizen" as UC1
    }
}

package "PERSISTENCE" as PERSISTENCE {
    package "GuestRepository"
    package "CitizenRepository"
    package "LocalAuthorityRepository"
    package "CaseOfficerRepository"
    package "PodcastEpisodeRepository"
}

package "DOMAIN" as DOMAIN {
    package "Guest"
    package "Citizen"
    package "LocalAuthority"
    package "CaseOfficer"
    package "PodcastEpisode"
}

package "TECHNICAL SERVICE" as TECHNICAL_SERVICE {
    package "DBSoulAndTalk"
}

UI ..> APPLICATION : using
UI ..> UC1 : using
APPLICATION ..> PERSISTENCE : using
PERSISTENCE ..> DOMAIN : using
PERSISTENCE ..> TECHNICAL_SERVICE : using database

UC1 ..> "CitizenRepository" : using
UC1 ..> "GuestRepository" : using
UC1 ..> "Citizen" : using
UC1 ..> "Guest" : using

"GuestRepository" ..> "Guest" : using
"CitizenRepository" ..> "Citizen" : using
"LocalAuthorityRepository" ..> "LocalAuthority" : using
"CaseOfficerRepository" ..> "CaseOfficer" : using
"PodcastEpisodeRepository" ..> "PodcastEpisode" : using

hide methods
hide fields
hide circle

@enduml