@startuml - UML DatabaseModel for Budweg
hide circle

/'Relationer
SPAREPARTS(<ins>SparePartId</ins> SparePartType, SparePartAmount)
STATION(<ins>StationId</ins>, StationType, StationsName, *SparePartId*)
BRAKECALIPER(<ins>CaliperId</ins>, CaliperType, CaliperStatus, Barcode, CaliperNumber, OrderNumber, Note, *StationId*)
'/
class "GUEST" <<table>>{
    {static} <<PK>> GuestId : Int
    {field} Name : NVarChar(50)
    {field} Phone : NVarChar(12)
    {field} Email : NVarChar(50)
    {field} ConsentStatus : NVarChar(50)
    //<<FK>> PodcastEpisodeId : Int//
    //<<FK>> CitizenId : Int//
    //<<FK>> JournalId : Int//
    {method} <<PK>> PK_GUEST()
    {method} <<FK>> FK_GUEST_JOURNAL()
}

class "CITIZEN" <<table>>{
    {static} <<PK>> CitizenId : Int
    {field} Name : NVarChar(50)
    {field} CprNumber : NVarChar(10)
    {field} WorkStatus : NVarChar(50)
    {field} WorkType : NVarChar(50)
    {field} ConsentStatus : Bit
    {field} CurrentStatus : NVarChar(50)
    {field} SpecialConsiderations : NVarChar(255)
    //<<FK>> CaseOfficerId : Int//
    {method} <<PK>> PK_CITIZEN()
    {method} <<FK>> FK_CITIZEN_CASEOFFICER()
}

class "LOCALAUTHORITY" <<table>>{
    {static} <<PK>> LocalAuthorityId : Int
    {field} LocalAuthorityName : NVarChar(50)
    {field} EANNumber : NVarChar(13)
    {method} <<PK>> PK_LOCALAUTHORITY()
}

class "CASEOFFICER" <<table>>{
    {static} <<PK>> CaseOfficerId : Int
    {field} Name : NVarChar(50)
    {field} Department : NVarChar(50)
    {field} Phone : NVarChar(12)
    {field} Email : NVarChar(50)
    //<<FK>> LocalAuthorityId : Int//
    {method} <<PK>> PK_CASEOFFICER()
    {method} <<FK>> FK_CASEOFFICER_LOCALAUTHORITY()
    
}

class "PODCASTEPISODE" <<table>>{
    {static} <<PK>> PodcastEpisodeId : Int
    {field} Title : NVarChar(50)
    {field} Date : DateTime2
    {field} Duration : Time
    {field} Status : NVarChar(255)
    {field} MeetingPlace : NVarChar(255)
    {field} Note : NVarChar(255)
    //<<FK>> GuestId : Int//
    //<<FK>> CaseOfficerId : Int//
    {method} <<PK>> PK_PODCASTEPISODE()
    {method} <<FK>> FK_PODCASTEPISODE_GUEST()
    {method} <<FK>> FK_PODCASTEPISODE_CASEOFFICER()
}

class "JOURNAL" <<table>>{
    {static} <<PK>> JournalId : Int
    {field} StartDate : DateTime2
    {field} EndDate : DateTime2
    {field} Contract : Bit
    {field} Note : NVarChar(255)
    {field} ActivityStatus : NVarChar(50)
    {method} <<PK>> PK_JOURNAL()
}
'relationer'
LOCALAUTHORITY "1" -- "0..*" CASEOFFICER
CASEOFFICER "1" -- "0..*" PODCASTEPISODE
CASEOFFICER "1" -- "0..*" CITIZEN
CITIZEN "1" -- "1" GUEST
PODCASTEPISODE "0..*" -- "1" GUEST
GUEST "0..*" -- "1" JOURNAL


@enduml