@startuml "Use Case Tabel for Soul&Talk"
@startsalt "Use Case Tabel for Soul&Talk"
{#
  **Use Case # ** | **Use Case Navn**
  UC1 | Opret profil til podcastepisode
  UC2 | Planlæg podcastepisode
  UC3 | Opdater borgerprofil
  UC4 | Se episodeoversigt
}
@enduml