@startuml - Use Case Diagram for Soul&Talk
left to right direction
actor "Product Owner" as m
rectangle Soul&Talk {
  usecase "Opret profil til podcast episode" as UC1
  usecase "Planlæg podcast-episode" as UC2
  usecase "Rediger eksisterende gæst til podcast-episode" as UC3
}
m --> UC1
m --> UC2
m --> UC3

@enduml