@startuml - Use Case Diagram for Soul&Talk
left to right direction
actor "Podcast Owner" as m
rectangle Soul&Talk {
  usecase "Opret profil til podcastepisode" as UC1
  usecase "Planlæg podcastepisode" as UC2
  usecase "Opdater borgerprofil" as UC3
  usecase "Se episodeoversigt" as UC4
}
m --> UC1
m --> UC2
m --> UC3
m --> UC4

@enduml