@startuml SSD 
title <u>UC1: Opret profil til podcast episode  </u>

Actor ":Podcast Owner" as PO
participant "<u>:System</u>" as System

PO -> System: OpretProfil(navn, telefon, email)

PO -> System: GemProfil (navn, telefon, email)

opt Hvis profil er en borger
    PO -> System: tilføjBorgerInformationer(CPR,jobStatus, osv.)
    
    loop Valideringsfejl eller profil findes (BorgerInformationer)
        System -->> PO: Viser Fejlmeddelelse
        PO -> System: retValideringsfejl(Borgerinformationer rettes)
    else Succes
        PO -> System: gemProfil()
        
    end
end

System -->> PO: Profil gemt


hide footbox

@enduml