@startuml SSD 
title <u>UC1: Opret borgerprofil til podcast episode  </u>

Actor ":PO" as PO
participant "<u>:System</u>" as System

PO -> System: OpretBorger(navn, CPR-Nummer, telefon, email)
PO -> System: AngivJobStatus(jobStatus) og Hensyn(hensynInformationer)
PO -> System: Uploader samtykkeerklæring
PO -> System: GemBorger (navn, CPR-Nummer, telefon, email)

alt informationer godkendt
System --> PO: Informationer er korrekte

else Informationer blev ikke godkendt

System --> PO: Informationer er inkorrekte
PO -> System: PO indtaster manglende informationer
PO -> System: GemBorger (navn, CPR-Nummer, telefon, email)
end
System --> PO: Borgerprofil er gemt


hide footbox

@enduml