@startuml
@startsalt
{
  == 1. Main Window (Soul and Talk)
  --
  [ Podcast episoder ]
  [ Gæste kartotek  ]
  --
  
  == 2. PodcastWindow (Liste over episoder)
  {
    [ Opret episode ] | [ Tilbage ]
    --
    **Episoder**
    {#
      Episode #42 | [ Rediger ]
      Episode #41 | [ Rediger ]
      Episode #40 | [ Rediger ]
    }
  }
  --
  
  == 3. CreatePodcastWindow (Opret/Rediger)
  {
    Titel:         | "                         "
    Dato:          | "16-04-2026"
    Varighed:      | "                         "
    Status:        | ^Planlagt^
    Moderator:     | "                         "
    Gæst:          | [ Tilføj gæst ]
    Sagsbehandler: | "                         "
    --
    Noter:
    {+
      .
      .
    }
    [ Gem ] | [ Annuller ]
  }
  --
  
  == 4. Select Guest (Vælg gæst til podcast)
  {
    Søg: | "Navn...                 "
    --
    {#
      <b>Navn</b>   | <b>Handling</b>
      Morten J.   | [ Vælg ]
      Lise L.     | [ Vælg ]
      Kasper B.   | [ Vælg ]
    }
    [ Luk ]
  }
  --
  
  == 5. GuestWindow (Gæste liste)
  {
    **Gæst liste** | [ Tilbage ]
    --
    {#
      Gæst 1 | [ Rediger ] | [ Slet ]
      Gæst 2 | [ Rediger ] | [ Slet ]
      Gæst 3 | [ Rediger ] | [ Slet ]
    }
    [ Opret ny gæst ]
  }
  --
  
  == 6. CreateGuestWindow (Opret/Rediger gæst)
  {
    Navn:       | "                         "
    Tlf:        | "                         "
    Email:      | "                         "
    CPR:        | "XXXXXX-XXXX"
    --
    Type: (X) Gæst ( ) Borger
    --
    [] Samtykke indhentet
    Besøgsstatus: | ^Afventer^
    Særlige hensyn: | "                     "
    --
    [ Gem ] | [ Luk ]
  }
  --
  
  == 7. Slet Dialog (Bekræftelse)
  {
    Er du sikker på, at du vil
    slette denne gæst?
    --
    [ JA, SLET ] | [ NEJ ]
  }
}
@endsalt
@enduml